/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

import CLASSESE.Analystes;
import CLASSESE.Centre_Gestions;
import BD.Connexion;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author KATALA
 */
public class ANALYSTE extends javax.swing.JPanel {

    Analystes a = new Analystes();
    Centre_Gestions c = new Centre_Gestions();

    /**
     * Creates new form ANALYSTE
     */
    public ANALYSTE() {
        initComponents();
        jScrollPane2.getHorizontalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane2.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane2.getViewport().setBackground(Color.white);

        jScrollPane1.getHorizontalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getViewport().setBackground(Color.white);

        a.remplir(TableAnalyste, "SELECT * FROM ANALYSTES");
        c.remplir(TableCentre, "SELECT * FROM centre_gestion");
        a.charger(Matricule_A);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        matricule = new javax.swing.JTextField();
        nom = new javax.swing.JTextField();
        postnom = new javax.swing.JTextField();
        prenom = new javax.swing.JTextField();
        telephone = new javax.swing.JTextField();
        grade = new javax.swing.JTextField();
        kButton9 = new keeptoo.KButton();
        kButton5 = new keeptoo.KButton();
        kButton4 = new keeptoo.KButton();
        kButton11 = new keeptoo.KButton();
        kButton16 = new keeptoo.KButton();
        jPanel5 = new javax.swing.JPanel();
        code_centre = new javax.swing.JTextField();
        nom_c = new javax.swing.JTextField();
        libelle = new javax.swing.JTextField();
        kButton10 = new keeptoo.KButton();
        kButton6 = new keeptoo.KButton();
        kButton7 = new keeptoo.KButton();
        Matricule_A = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        kButton12 = new keeptoo.KButton();
        jLabel5 = new javax.swing.JLabel();
        kButton15 = new keeptoo.KButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TableCentre = new rojerusan.RSTableMetro();
        jScrollPane2 = new javax.swing.JScrollPane();
        TableAnalyste = new rojerusan.RSTableMetro();
        rechercheA = new javax.swing.JTextField();
        rechercheC = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kButton13 = new keeptoo.KButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 26, 83));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LA GESTION DES ANALYSTES  ET AFFECTATION");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 26, 83), 1, true), "ANALYSTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N

        matricule.setForeground(new java.awt.Color(0, 26, 83));
        matricule.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "MATRICULE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        matricule.setOpaque(false);
        matricule.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                matriculeMouseClicked(evt);
            }
        });
        matricule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matriculeActionPerformed(evt);
            }
        });

        nom.setForeground(new java.awt.Color(0, 26, 83));
        nom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "NOM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        nom.setOpaque(false);
        nom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nomMouseClicked(evt);
            }
        });
        nom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nomActionPerformed(evt);
            }
        });

        postnom.setForeground(new java.awt.Color(0, 26, 83));
        postnom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "POSTNOM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        postnom.setOpaque(false);
        postnom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                postnomMouseClicked(evt);
            }
        });
        postnom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                postnomActionPerformed(evt);
            }
        });

        prenom.setForeground(new java.awt.Color(0, 26, 83));
        prenom.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "PRENOM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        prenom.setOpaque(false);
        prenom.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                prenomMouseClicked(evt);
            }
        });
        prenom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                prenomActionPerformed(evt);
            }
        });

        telephone.setForeground(new java.awt.Color(0, 26, 83));
        telephone.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "TELEPHONE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        telephone.setOpaque(false);
        telephone.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                telephoneMouseClicked(evt);
            }
        });
        telephone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telephoneActionPerformed(evt);
            }
        });

        grade.setForeground(new java.awt.Color(0, 26, 83));
        grade.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "GRADE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        grade.setOpaque(false);
        grade.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                gradeMouseClicked(evt);
            }
        });
        grade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gradeActionPerformed(evt);
            }
        });

        kButton9.setText("SUPPRIMER");
        kButton9.setBorderPainted(false);
        kButton9.setkAllowGradient(false);
        kButton9.setkAllowTab(false);
        kButton9.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        kButton9.setkBorderRadius(15);
        kButton9.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton9.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton9.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton9.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton9.setOpaque(false);
        kButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton9ActionPerformed(evt);
            }
        });

        kButton5.setText("MODIFIER");
        kButton5.setBorderPainted(false);
        kButton5.setkAllowGradient(false);
        kButton5.setkAllowTab(false);
        kButton5.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton5.setkBorderRadius(15);
        kButton5.setkHoverColor(new java.awt.Color(0, 176, 80));
        kButton5.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton5.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton5.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton5.setOpaque(false);
        kButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton5ActionPerformed(evt);
            }
        });

        kButton4.setText("AJOUTER");
        kButton4.setBorderPainted(false);
        kButton4.setkAllowGradient(false);
        kButton4.setkAllowTab(false);
        kButton4.setkBackGroundColor(new java.awt.Color(0, 176, 80));
        kButton4.setkBorderRadius(15);
        kButton4.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton4.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton4.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton4.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton4.setOpaque(false);
        kButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton4MouseClicked(evt);
            }
        });
        kButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton4ActionPerformed(evt);
            }
        });

        kButton11.setText("INITIALISER");
        kButton11.setBorderPainted(false);
        kButton11.setkAllowGradient(false);
        kButton11.setkAllowTab(false);
        kButton11.setkBackGroundColor(new java.awt.Color(0, 51, 51));
        kButton11.setkBorderRadius(15);
        kButton11.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton11.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton11.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton11.setOpaque(false);
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });

        kButton16.setText("IMPRIMER");
        kButton16.setBorderPainted(false);
        kButton16.setkAllowGradient(false);
        kButton16.setkAllowTab(false);
        kButton16.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        kButton16.setkBorderRadius(15);
        kButton16.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton16.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton16.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton16.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton16.setOpaque(false);
        kButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton16ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(matricule)
                    .addComponent(nom)
                    .addComponent(postnom)
                    .addComponent(prenom)
                    .addComponent(telephone)
                    .addComponent(grade)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(kButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kButton16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(kButton16, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(matricule, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(postnom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(prenom, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(13, 13, 13)
                .addComponent(telephone, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(grade, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(kButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(123, Short.MAX_VALUE))
        );

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 26, 83), 1, true), "CENTRE DE GESTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N

        code_centre.setForeground(new java.awt.Color(0, 26, 83));
        code_centre.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "CODE CENTRE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        code_centre.setOpaque(false);
        code_centre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                code_centreMouseClicked(evt);
            }
        });
        code_centre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                code_centreActionPerformed(evt);
            }
        });

        nom_c.setForeground(new java.awt.Color(0, 26, 83));
        nom_c.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "NOM", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        nom_c.setOpaque(false);
        nom_c.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                nom_cMouseClicked(evt);
            }
        });
        nom_c.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nom_cActionPerformed(evt);
            }
        });

        libelle.setForeground(new java.awt.Color(0, 26, 83));
        libelle.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "LIBELLE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        libelle.setOpaque(false);
        libelle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                libelleMouseClicked(evt);
            }
        });
        libelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                libelleActionPerformed(evt);
            }
        });

        kButton10.setText("SUPPRIMER");
        kButton10.setBorderPainted(false);
        kButton10.setkAllowGradient(false);
        kButton10.setkAllowTab(false);
        kButton10.setkBackGroundColor(new java.awt.Color(255, 0, 0));
        kButton10.setkBorderRadius(15);
        kButton10.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton10.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton10.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton10.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton10.setOpaque(false);
        kButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton10ActionPerformed(evt);
            }
        });

        kButton6.setText("MODIFIER");
        kButton6.setBorderPainted(false);
        kButton6.setkAllowGradient(false);
        kButton6.setkAllowTab(false);
        kButton6.setkBackGroundColor(new java.awt.Color(102, 102, 102));
        kButton6.setkBorderRadius(15);
        kButton6.setkHoverColor(new java.awt.Color(0, 176, 80));
        kButton6.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton6.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton6.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton6.setOpaque(false);
        kButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton6ActionPerformed(evt);
            }
        });

        kButton7.setText("AJOUTER");
        kButton7.setBorderPainted(false);
        kButton7.setkAllowGradient(false);
        kButton7.setkAllowTab(false);
        kButton7.setkBackGroundColor(new java.awt.Color(0, 176, 80));
        kButton7.setkBorderRadius(15);
        kButton7.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton7.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton7.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton7.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton7.setOpaque(false);
        kButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kButton7MouseClicked(evt);
            }
        });
        kButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton7ActionPerformed(evt);
            }
        });

        jLabel4.setForeground(new java.awt.Color(0, 26, 83));
        jLabel4.setText("MATRICULE ANALYSTE");

        kButton12.setText("INITIALISER");
        kButton12.setBorderPainted(false);
        kButton12.setkAllowGradient(false);
        kButton12.setkAllowTab(false);
        kButton12.setkBackGroundColor(new java.awt.Color(0, 51, 51));
        kButton12.setkBorderRadius(15);
        kButton12.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton12.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton12.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton12.setOpaque(false);
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icons8_update.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        kButton15.setText("IMPRIMER");
        kButton15.setBorderPainted(false);
        kButton15.setkAllowGradient(false);
        kButton15.setkAllowTab(false);
        kButton15.setkBackGroundColor(new java.awt.Color(153, 153, 153));
        kButton15.setkBorderRadius(15);
        kButton15.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton15.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton15.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton15.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton15.setOpaque(false);
        kButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton15ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Matricule_A, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5))
                            .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(nom_c, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(code_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(kButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(kButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(kButton15, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addComponent(code_centre, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nom_c, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(libelle, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Matricule_A, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addComponent(kButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        TableCentre.setForeground(new java.awt.Color(255, 255, 255));
        TableCentre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableCentre.setAltoHead(30);
        TableCentre.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TableCentre.setColorBackgoundHead(new java.awt.Color(0, 26, 83));
        TableCentre.setColorBordeHead(new java.awt.Color(0, 153, 255));
        TableCentre.setColorFilasBackgound2(new java.awt.Color(238, 238, 238));
        TableCentre.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        TableCentre.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        TableCentre.setFocusable(false);
        TableCentre.setGrosorBordeFilas(0);
        TableCentre.setGrosorBordeHead(0);
        TableCentre.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableCentre.setMultipleSeleccion(false);
        TableCentre.setRowHeight(20);
        TableCentre.setShowHorizontalLines(false);
        TableCentre.setShowVerticalLines(false);
        TableCentre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableCentreMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TableCentre);

        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        TableAnalyste.setForeground(new java.awt.Color(255, 255, 255));
        TableAnalyste.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TableAnalyste.setAltoHead(30);
        TableAnalyste.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        TableAnalyste.setColorBackgoundHead(new java.awt.Color(0, 26, 83));
        TableAnalyste.setColorBordeHead(new java.awt.Color(0, 153, 255));
        TableAnalyste.setColorFilasBackgound2(new java.awt.Color(238, 238, 238));
        TableAnalyste.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        TableAnalyste.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        TableAnalyste.setFocusable(false);
        TableAnalyste.setGrosorBordeFilas(0);
        TableAnalyste.setGrosorBordeHead(0);
        TableAnalyste.setIntercellSpacing(new java.awt.Dimension(0, 0));
        TableAnalyste.setMultipleSeleccion(false);
        TableAnalyste.setRowHeight(20);
        TableAnalyste.setShowHorizontalLines(false);
        TableAnalyste.setShowVerticalLines(false);
        TableAnalyste.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableAnalysteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TableAnalyste);

        rechercheA.setForeground(new java.awt.Color(0, 26, 83));
        rechercheA.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "RECHERCHE ANALYSTE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        rechercheA.setOpaque(false);
        rechercheA.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rechercheACaretUpdate(evt);
            }
        });
        rechercheA.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheAMouseClicked(evt);
            }
        });
        rechercheA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheAActionPerformed(evt);
            }
        });

        rechercheC.setForeground(new java.awt.Color(0, 26, 83));
        rechercheC.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "RECHERCHE CENTRE DE GESTION", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        rechercheC.setOpaque(false);
        rechercheC.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rechercheCCaretUpdate(evt);
            }
        });
        rechercheC.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rechercheCMouseClicked(evt);
            }
        });
        rechercheC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rechercheCActionPerformed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icons8_update.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icons8_update.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        kButton13.setForeground(new java.awt.Color(0, 26, 83));
        kButton13.setText("TABLEAU DE BORD");
        kButton13.setBorderPainted(false);
        kButton13.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        kButton13.setkAllowGradient(false);
        kButton13.setkBackGroundColor(new java.awt.Color(255, 255, 255));
        kButton13.setkBorderRadius(15);
        kButton13.setkHoverColor(new java.awt.Color(0, 26, 83));
        kButton13.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton13.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton13.setkSelectedColor(new java.awt.Color(0, 26, 83));
        kButton13.setOpaque(false);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 582, Short.MAX_VALUE)
                                .addContainerGap())
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(kButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 278, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rechercheA, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jScrollPane2)
                                .addContainerGap())))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(rechercheC, javax.swing.GroupLayout.PREFERRED_SIZE, 344, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(rechercheA, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(kButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(rechercheC, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void matriculeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_matriculeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeMouseClicked

    private void matriculeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matriculeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_matriculeActionPerformed

    private void nomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nomMouseClicked

    private void nomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nomActionPerformed

    private void postnomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_postnomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_postnomMouseClicked

    private void postnomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_postnomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_postnomActionPerformed

    private void prenomMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_prenomMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomMouseClicked

    private void prenomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_prenomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_prenomActionPerformed

    private void telephoneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_telephoneMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneMouseClicked

    private void telephoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telephoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telephoneActionPerformed

    private void gradeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_gradeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeMouseClicked

    private void gradeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gradeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gradeActionPerformed

    private void code_centreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_code_centreMouseClicked
        // TODO add your handling code here:
        //DateCourante();
    }//GEN-LAST:event_code_centreMouseClicked

    private void code_centreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_code_centreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_code_centreActionPerformed

    private void nom_cMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nom_cMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_cMouseClicked

    private void nom_cActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nom_cActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nom_cActionPerformed

    private void libelleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_libelleMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleMouseClicked

    private void libelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_libelleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_libelleActionPerformed

    private void rechercheAMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheAMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheAMouseClicked

    private void rechercheAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheAActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheAActionPerformed

    private void rechercheCMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rechercheCMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheCMouseClicked

    private void rechercheCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rechercheCActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rechercheCActionPerformed

    private void kButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton9ActionPerformed
        // TODO add your handling code here:
        a.setMatricule(matricule.getText());
        a.setNom(nom.getText());
        a.setPostnom(postnom.getText());
        a.setPrenom(prenom.getText());
        a.setTelephone(telephone.getText());
        a.setGrade(grade.getText());

        a.supprimer();
    }//GEN-LAST:event_kButton9ActionPerformed

    private void kButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton5ActionPerformed
        // TODO add your handling code here:

        a.setMatricule(matricule.getText());
        a.setNom(nom.getText());
        a.setPostnom(postnom.getText());
        a.setPrenom(prenom.getText());
        a.setTelephone(telephone.getText());
        a.setGrade(grade.getText());

        a.modifier();
    }//GEN-LAST:event_kButton5ActionPerformed

    private void kButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton4MouseClicked

    private void kButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton4ActionPerformed
        // TODO add your handling code here:
        a.setMatricule(matricule.getText());
        a.setNom(nom.getText());
        a.setPostnom(postnom.getText());
        a.setPrenom(prenom.getText());
        a.setTelephone(telephone.getText());
        a.setGrade(grade.getText());
        a.setPasswords(matricule.getText());

        a.ajouter();
    }//GEN-LAST:event_kButton4ActionPerformed

    private void kButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton10ActionPerformed
        // TODO add your handling code here:
        c.setCode_centre(code_centre.getText());
        c.setNom(nom_c.getText());
        c.setLibelle(libelle.getText());
        c.setMatricule(Matricule_A.getSelectedItem().toString());

        c.supprimer();
    }//GEN-LAST:event_kButton10ActionPerformed

    private void kButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton6ActionPerformed
        // TODO add your handling code here:
        c.setCode_centre(code_centre.getText());
        c.setNom(nom_c.getText());
        c.setLibelle(libelle.getText());
        c.setMatricule(Matricule_A.getSelectedItem().toString());

        c.modifier();
    }//GEN-LAST:event_kButton6ActionPerformed

    private void kButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kButton7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kButton7MouseClicked

    private void kButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton7ActionPerformed
        // TODO add your handling code here:
        c.setCode_centre(code_centre.getText());
        c.setNom(nom_c.getText());
        c.setLibelle(libelle.getText());
        c.setMatricule(Matricule_A.getSelectedItem().toString());

        c.ajouter();
    }//GEN-LAST:event_kButton7ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        matricule.setText("");
        nom.setText("");
        postnom.setText("");
        prenom.setText("");
        telephone.setText("");
        grade.setText("");
        a.remplir(TableAnalyste, "SELECT * FROM ANALYSTES");

    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
        code_centre.setText("");
        nom_c.setText("");
        libelle.setText("");
        Matricule_A.setSelectedItem("");
        c.remplir(TableCentre, "SELECT * FROM centre_gestion");
    }//GEN-LAST:event_kButton12ActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        a.remplir(TableAnalyste, "SELECT * FROM ANALYSTES");
    }//GEN-LAST:event_jLabel2MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        c.remplir(TableCentre, "SELECT * FROM centre_gestion");
    }//GEN-LAST:event_jLabel3MouseClicked

    private void TableAnalysteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableAnalysteMouseClicked
        // TODO add your handling code here:
        int ligne = TableAnalyste.getSelectedRow();

        matricule.setText(TableAnalyste.getValueAt(ligne, 0).toString());
        nom.setText(TableAnalyste.getValueAt(ligne, 1).toString());
        postnom.setText(TableAnalyste.getValueAt(ligne, 2).toString());
        prenom.setText(TableAnalyste.getValueAt(ligne, 3).toString());
        telephone.setText(TableAnalyste.getValueAt(ligne, 4).toString());
        grade.setText(TableAnalyste.getValueAt(ligne, 5).toString());

    }//GEN-LAST:event_TableAnalysteMouseClicked

    private void TableCentreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableCentreMouseClicked
        // TODO add your handling code here:
        int ligne = TableCentre.getSelectedRow();

        code_centre.setText(TableCentre.getValueAt(ligne, 0).toString());
        nom_c.setText(TableCentre.getValueAt(ligne, 1).toString());
        libelle.setText(TableCentre.getValueAt(ligne, 2).toString());
        Matricule_A.setSelectedItem(TableCentre.getValueAt(ligne, 3).toString());

    }//GEN-LAST:event_TableCentreMouseClicked

    private void rechercheACaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_rechercheACaretUpdate
        // TODO add your handling code here:
        a.remplir(TableAnalyste, "select* from analystes where matricule like '%" + rechercheA.getText() + "%' or nom like '%" + rechercheA.getText() + "%' or prenom like '%" + rechercheA.getText() + "%'");
    }//GEN-LAST:event_rechercheACaretUpdate

    private void rechercheCCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_rechercheCCaretUpdate
        // TODO add your handling code here:
        c.remplir(TableCentre, "select* from centre_gestion where code_centre like '%" + rechercheC.getText() + "%' or nom like '%" + rechercheC.getText() + "%' or libelle like '%" + rechercheA.getText() + "%'");

    }//GEN-LAST:event_rechercheCCaretUpdate

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        a.charger(Matricule_A);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
        new TABLEAU().setVisible(true);
    }//GEN-LAST:event_kButton13ActionPerformed

    private void kButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton15ActionPerformed
        // TODO add your handling code here:
        try {
            //String rapport = "ListeBIOLOGIQUE.jasper";
            JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\AFFECTATION.jrxml");
            JasperReport rapport = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(ANALYSTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton15ActionPerformed

    private void kButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton16ActionPerformed
        // TODO add your handling code here:
        try {
            //String rapport = "ListeBIOLOGIQUE.jasper";
            JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\ANALYSTE.jrxml");
            JasperReport rapport = JasperCompileManager.compileReport(jd);
            JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
            JasperViewer.viewReport(jp, false);
        } catch (JRException ex) {
            Logger.getLogger(ANALYSTE.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton16ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JComboBox<String> Matricule_A;
    private rojerusan.RSTableMetro TableAnalyste;
    private rojerusan.RSTableMetro TableCentre;
    public javax.swing.JTextField code_centre;
    public javax.swing.JTextField grade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KButton kButton10;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private keeptoo.KButton kButton15;
    private keeptoo.KButton kButton16;
    private keeptoo.KButton kButton4;
    private keeptoo.KButton kButton5;
    private keeptoo.KButton kButton6;
    private keeptoo.KButton kButton7;
    private keeptoo.KButton kButton9;
    public javax.swing.JTextField libelle;
    public javax.swing.JTextField matricule;
    public javax.swing.JTextField nom;
    public javax.swing.JTextField nom_c;
    public javax.swing.JTextField postnom;
    public javax.swing.JTextField prenom;
    public javax.swing.JTextField rechercheA;
    public javax.swing.JTextField rechercheC;
    public javax.swing.JTextField telephone;
    // End of variables declaration//GEN-END:variables
}
