/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

import BD.Connexion;
import CLASSESE.Travailleurs;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author KATALA
 */
public class VOIR_TRAVAILLEURS extends javax.swing.JPanel {

    /**
     * Creates new form VOIR_TRAVAILLEURS
     */
    Travailleurs t = new Travailleurs();
    MODIF_TRAVAILLEURS MT = new MODIF_TRAVAILLEURS();
    MENUS M = new MENUS();

    public VOIR_TRAVAILLEURS() {
        initComponents();
        jScrollPane1.getHorizontalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getViewport().setBackground(Color.white);
        MATRICULE.setVisible(false);
        MATRICULE.setText(MENUS.vrai);

        if (MENUS.grades.equals("analyste")) {
            t.remplir(Table, "SELECT * FROM travailleurs where matricule='" + MENUS.vrai + "'");
        } else {
            t.remplir(Table, "SELECT * FROM travailleurs");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new rojerusan.RSTableMetro();
        kButton11 = new keeptoo.KButton();
        kButton12 = new keeptoo.KButton();
        kButton13 = new keeptoo.KButton();
        MATRICULE = new javax.swing.JTextField();
        Annee = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(0, 26, 83));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES TRAVAILLEURS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        recherche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recherche.setForeground(new java.awt.Color(102, 102, 102));
        recherche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        recherche.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rechercheCaretUpdate(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("RECHERCHER PAR :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icons8_update.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titre 1", "Titre 2", "Titre 3", "Titre 4", "Titre 5", "Titre 6"
            }
        ));
        Table.setAltoHead(30);
        Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table.setColorBackgoundHead(new java.awt.Color(0, 26, 83));
        Table.setColorBordeHead(new java.awt.Color(0, 176, 80));
        Table.setColorFilasBackgound2(new java.awt.Color(238, 238, 238));
        Table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Table.setColorSelBackgound(new java.awt.Color(0, 176, 80));
        Table.setFocusable(false);
        Table.setGrosorBordeFilas(0);
        Table.setGrosorBordeHead(0);
        Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Table.setMultipleSeleccion(false);
        Table.setRowHeight(20);
        Table.setShowHorizontalLines(false);
        Table.setShowVerticalLines(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        kButton11.setText("IMPRIMER TOUT");
        kButton11.setBorderPainted(false);
        kButton11.setkAllowGradient(false);
        kButton11.setkAllowTab(false);
        kButton11.setkBackGroundColor(new java.awt.Color(0, 26, 83));
        kButton11.setkBorderRadius(15);
        kButton11.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton11.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton11.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton11.setOpaque(false);
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });

        kButton12.setText("IMPRIMER UN CENTRE");
        kButton12.setBorderPainted(false);
        kButton12.setkAllowGradient(false);
        kButton12.setkAllowTab(false);
        kButton12.setkBackGroundColor(new java.awt.Color(0, 26, 83));
        kButton12.setkBorderRadius(15);
        kButton12.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton12.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton12.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton12.setOpaque(false);
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });

        kButton13.setText("IMPRIMER UN MOIS");
        kButton13.setBorderPainted(false);
        kButton13.setkAllowGradient(false);
        kButton13.setkAllowTab(false);
        kButton13.setkBackGroundColor(new java.awt.Color(0, 26, 83));
        kButton13.setkBorderRadius(15);
        kButton13.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton13.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton13.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton13.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton13.setOpaque(false);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });

        Annee.setForeground(new java.awt.Color(0, 26, 83));
        Annee.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "ANNEE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        Annee.setOpaque(false);
        Annee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnneeMouseClicked(evt);
            }
        });
        Annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnneeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1254, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MATRICULE, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Annee, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(recherche, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Annee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(kButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(MATRICULE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 514, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void rechercheCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_rechercheCaretUpdate
        // TODO add your handling code here:
        //        ex.remplir(Table, "SELECT * FROM examautres where id_examAutres like '%" + recherche.getText() + "%'");
    }//GEN-LAST:event_rechercheCaretUpdate

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (MENUS.grades.equals("analyste")) {
            t.remplir(Table, "SELECT * FROM travailleurs where matricule='" + MENUS.vrai + "'");
        } else {
            t.remplir(Table, "SELECT * FROM travailleurs");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        // TODO add your handling code here:
        try {
            MT.setVisible(true);
            int ligne = Table.getSelectedRow();
            MT.num.setText(Table.getValueAt(ligne, 0).toString());
            MT.num1.setText(Table.getValueAt(ligne, 1).toString());
            MT.num10.setText(Table.getValueAt(ligne, 2).toString());
            MT.num2.setText(Table.getValueAt(ligne, 3).toString());
            MT.num3.setText(Table.getValueAt(ligne, 4).toString());
            MT.num4.setText(Table.getValueAt(ligne, 5).toString());
            MT.num5.setText(Table.getValueAt(ligne, 6).toString());
            MT.num6.setText(Table.getValueAt(ligne, 7).toString());
            MT.num7.setText(Table.getValueAt(ligne, 8).toString());
            MT.num8.setText(Table.getValueAt(ligne, 9).toString());
            MT.num9.setText(Table.getValueAt(ligne, 10).toString());
            MT.num12.setText(Table.getValueAt(ligne, 11).toString());
            MT.num14.setText(Table.getValueAt(ligne, 12).toString());
            MT.num15.setText(Table.getValueAt(ligne, 13).toString());
            MT.num16.setText(Table.getValueAt(ligne, 14).toString());
            MT.num17.setText(Table.getValueAt(ligne, 15).toString());
            MT.num18.setText(Table.getValueAt(ligne, 16).toString());
            MT.num25.setText(Table.getValueAt(ligne, 17).toString());
            MT.num24.setText(Table.getValueAt(ligne, 18).toString());
            MT.num23.setText(Table.getValueAt(ligne, 19).toString());
            MT.num22.setText(Table.getValueAt(ligne, 20).toString());
            MT.num41.setText(Table.getValueAt(ligne, 21).toString());
            MT.num40.setText(Table.getValueAt(ligne, 22).toString());
            MT.num39.setText(Table.getValueAt(ligne, 23).toString());
            MT.num38.setText(Table.getValueAt(ligne, 24).toString());
            MT.num37.setText(Table.getValueAt(ligne, 25).toString());
            MT.num36.setText(Table.getValueAt(ligne, 26).toString());
            MT.num35.setText(Table.getValueAt(ligne, 27).toString());
            MT.num34.setText(Table.getValueAt(ligne, 28).toString());
            MT.num33.setText(Table.getValueAt(ligne, 29).toString());
            MT.num32.setText(Table.getValueAt(ligne, 30).toString());
            MT.num42.setText(Table.getValueAt(ligne, 31).toString());
            MT.num43.setText(Table.getValueAt(ligne, 32).toString());
            MT.num44.setText(Table.getValueAt(ligne, 33).toString());
            MT.num45.setText(Table.getValueAt(ligne, 34).toString());
            MT.num46.setText(Table.getValueAt(ligne, 35).toString());
            MT.num47.setText(Table.getValueAt(ligne, 36).toString());
            MT.num48.setText(Table.getValueAt(ligne, 37).toString());
            MT.num49.setText(Table.getValueAt(ligne, 38).toString());
            MT.num50.setText(Table.getValueAt(ligne, 39).toString());
            MT.num51.setText(Table.getValueAt(ligne, 40).toString());
            MT.num61.setText(Table.getValueAt(ligne, 41).toString());
            MT.num60.setText(Table.getValueAt(ligne, 42).toString());
            MT.num59.setText(Table.getValueAt(ligne, 43).toString());
            MT.num58.setText(Table.getValueAt(ligne, 44).toString());
            MT.num57.setText(Table.getValueAt(ligne, 45).toString());
            MT.num56.setText(Table.getValueAt(ligne, 46).toString());
            MT.num55.setText(Table.getValueAt(ligne, 47).toString());
            MT.num54.setText(Table.getValueAt(ligne, 48).toString());
            MT.num53.setText(Table.getValueAt(ligne, 49).toString());
            MT.num52.setText(Table.getValueAt(ligne, 50).toString());
            MT.num71.setText(Table.getValueAt(ligne, 51).toString());
            MT.num70.setText(Table.getValueAt(ligne, 52).toString());
            MT.num69.setText(Table.getValueAt(ligne, 53).toString());
            MT.num68.setText(Table.getValueAt(ligne, 54).toString());
            MT.num67.setText(Table.getValueAt(ligne, 55).toString());
            MT.num66.setText(Table.getValueAt(ligne, 56).toString());
            MT.num65.setText(Table.getValueAt(ligne, 57).toString());
            MT.num64.setText(Table.getValueAt(ligne, 58).toString());
            MT.num63.setText(Table.getValueAt(ligne, 59).toString());
            MT.num62.setText(Table.getValueAt(ligne, 60).toString());
            MT.num81.setText(Table.getValueAt(ligne, 61).toString());
            MT.num80.setText(Table.getValueAt(ligne, 62).toString());
            MT.num79.setText(Table.getValueAt(ligne, 63).toString());
            MT.num78.setText(Table.getValueAt(ligne, 64).toString());
            MT.num77.setText(Table.getValueAt(ligne, 65).toString());
            MT.num76.setText(Table.getValueAt(ligne, 66).toString());
            MT.num75.setText(Table.getValueAt(ligne, 67).toString());
            MT.num74.setText(Table.getValueAt(ligne, 68).toString());
            MT.num73.setText(Table.getValueAt(ligne, 69).toString());
            MT.num72.setText(Table.getValueAt(ligne, 70).toString());
            MT.num91.setText(Table.getValueAt(ligne, 71).toString());
            MT.num90.setText(Table.getValueAt(ligne, 72).toString());
            MT.num89.setText(Table.getValueAt(ligne, 73).toString());
            MT.num88.setText(Table.getValueAt(ligne, 74).toString());
            MT.num87.setText(Table.getValueAt(ligne, 75).toString());
            MT.num86.setText(Table.getValueAt(ligne, 76).toString());
            MT.num85.setText(Table.getValueAt(ligne, 77).toString());
            MT.num84.setText(Table.getValueAt(ligne, 78).toString());
            MT.num83.setText(Table.getValueAt(ligne, 79).toString());
            MT.num82.setText(Table.getValueAt(ligne, 80).toString());
            MT.num101.setText(Table.getValueAt(ligne, 81).toString());
            MT.num100.setText(Table.getValueAt(ligne, 82).toString());
            MT.num99.setText(Table.getValueAt(ligne, 83).toString());
            MT.num98.setText(Table.getValueAt(ligne, 84).toString());
            MT.num97.setText(Table.getValueAt(ligne, 85).toString());
            MT.num96.setText(Table.getValueAt(ligne, 86).toString());
            MT.num95.setText(Table.getValueAt(ligne, 87).toString());
            MT.num94.setText(Table.getValueAt(ligne, 88).toString());
            MT.num93.setText(Table.getValueAt(ligne, 89).toString());
            MT.num92.setText(Table.getValueAt(ligne, 90).toString());
            MT.num111.setText(Table.getValueAt(ligne, 91).toString());
            MT.num110.setText(Table.getValueAt(ligne, 92).toString());
            MT.num109.setText(Table.getValueAt(ligne, 93).toString());
            MT.num108.setText(Table.getValueAt(ligne, 94).toString());
            MT.num107.setText(Table.getValueAt(ligne, 95).toString());
            MT.num106.setText(Table.getValueAt(ligne, 96).toString());
            MT.num105.setText(Table.getValueAt(ligne, 97).toString());
            MT.num104.setText(Table.getValueAt(ligne, 98).toString());
            MT.num103.setText(Table.getValueAt(ligne, 99).toString());
            MT.num102.setText(Table.getValueAt(ligne, 100).toString());
            MT.num114.setText(Table.getValueAt(ligne, 101).toString());
            MT.num113.setText(Table.getValueAt(ligne, 102).toString());
            MT.moisCB.setSelectedItem(Table.getValueAt(ligne, 103).toString());
            MT.Annee.setText(Table.getValueAt(ligne, 104).toString());
            MT.Code_centre.setSelectedItem(Table.getValueAt(ligne, 105).toString());
            //MT.num112.setText(Table.getValueAt(ligne, 106).toString());

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de retoure : " + e.getMessage());
        }
    }//GEN-LAST:event_TableMouseClicked

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        try {
            if (MENUS.grades.equals("analyste")) {
                String query = "SELECT c.nom,\n"
                        + "	t.Trav_au_fichier1,\n"
                        + "	t.Nouvelles_immatriculations1,\n"
                        + "    t.Trav_se_rap_aux_employeurs_actifs,\n"
                        + "    t.Trav_se_rap_aux_employeurs_ayant_declare,\n"
                        + "    t.Trav_se_rap_aux_employ_ayant_cotise,\n"
                        + "    t.Trav_se_rap_aux_employeurs_en_cessation_d_act,\n"
                        + "    t.MS_des_remu_soumises_cotisation,\n"
                        + "    t.mois,\n"
                        + "    t.annee\n"
                        + "FROM travailleurs as t\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=t.Code_centre\n"
                        + "WHERE t.annee='" + Annee.getText() + "' AND t.Matricule='" + MATRICULE.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\TRAVAILLEURTOUSMAT.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);

            } else {

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\TRAVAILLEURTOUS.jrxml");
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                String valeur = Annee.getText() + "%";
                Map param = new HashMap();
                param.put("ID", valeur);
                JasperPrint jp = JasperFillManager.fillReport(rapport, param, new Connexion().con());
                JasperViewer.viewReport(jp, false);
            }

        } catch (JRException ex) {
            Logger.getLogger(VOIR_TRAVAILLEURS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton11ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
        try {
            if (MENUS.grades.equals("analyste")) {
                String query = "SELECT c.Code_centre,\n"
                        + "	c.nom,\n"
                        + "	t.Trav_au_fichier1,\n"
                        + "	t.Nouvelles_immatriculations1,\n"
                        + "    t.Trav_se_rap_aux_employeurs_actifs,\n"
                        + "    t.Trav_se_rap_aux_employeurs_ayant_declare,\n"
                        + "    t.Trav_se_rap_aux_employ_ayant_cotise,\n"
                        + "    t.Trav_se_rap_aux_employeurs_en_cessation_d_act,\n"
                        + "    t.MS_des_remu_soumises_cotisation,\n"
                        + "    t.mois,\n"
                        + "    t.annee\n"
                        + "FROM travailleurs as t\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=t.Code_centre\n"
                        + "WHERE t.annee='" + Annee.getText() + "' AND t.Code_centre='" + recherche.getText() + "' AND t.Matricule='" + MATRICULE.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\TRAVAILLEURCENTREMAT.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);

            } else {

                String query = "SELECT c.Code_centre,\n"
                        + "	c.nom,\n"
                        + "	t.Trav_au_fichier1,\n"
                        + "	t.Nouvelles_immatriculations1,\n"
                        + "    t.Trav_se_rap_aux_employeurs_actifs,\n"
                        + "    t.Trav_se_rap_aux_employeurs_ayant_declare,\n"
                        + "    t.Trav_se_rap_aux_employ_ayant_cotise,\n"
                        + "    t.Trav_se_rap_aux_employeurs_en_cessation_d_act,\n"
                        + "    t.MS_des_remu_soumises_cotisation,\n"
                        + "    t.mois,\n"
                        + "    t.annee\n"
                        + "FROM travailleurs as t\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=t.Code_centre\n"
                        + "WHERE t.annee='" + Annee.getText() + "' AND t.Code_centre='" + recherche.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\TRAVAILLEURCENTRE.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);
            }

        } catch (JRException ex) {
            Logger.getLogger(VOIR_TRAVAILLEURS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton12ActionPerformed

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
        try {
            if (MENUS.grades.equals("analyste")) {
                String query = "SELECT\n"
                        + "	c.nom,\n"
                        + "	t.Trav_au_fichier1,\n"
                        + "	t.Nouvelles_immatriculations1,\n"
                        + "    t.Trav_se_rap_aux_employeurs_actifs,\n"
                        + "    t.Trav_se_rap_aux_employeurs_ayant_declare,\n"
                        + "    t.Trav_se_rap_aux_employ_ayant_cotise,\n"
                        + "    t.Trav_se_rap_aux_employeurs_en_cessation_d_act,\n"
                        + "    t.MS_des_remu_soumises_cotisation,\n"
                        + "    t.mois,\n"
                        + "    t.annee\n"
                        + "FROM travailleurs as t\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=t.Code_centre\n"
                        + "WHERE t.annee='" + Annee.getText() + "' AND t.mois='" + recherche.getText() + "' AND t.Matricule='" + MATRICULE.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\TRAVAILLEURMOISMAT.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);

            } else {

                String query = "SELECT\n"
                        + "	c.nom,\n"
                        + "	t.Trav_au_fichier1,\n"
                        + "	t.Nouvelles_immatriculations1,\n"
                        + "    t.Trav_se_rap_aux_employeurs_actifs,\n"
                        + "    t.Trav_se_rap_aux_employeurs_ayant_declare,\n"
                        + "    t.Trav_se_rap_aux_employ_ayant_cotise,\n"
                        + "    t.Trav_se_rap_aux_employeurs_en_cessation_d_act,\n"
                        + "    t.MS_des_remu_soumises_cotisation,\n"
                        + "    t.mois,\n"
                        + "    t.annee\n"
                        + "FROM travailleurs as t\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=t.Code_centre\n"
                        + "WHERE t.annee='" + Annee.getText() + "' AND t.mois='" + recherche.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\TRAVAILLEURMOIS.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);
            }

        } catch (JRException ex) {
            Logger.getLogger(VOIR_TRAVAILLEURS.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton13ActionPerformed

    private void AnneeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnneeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AnneeMouseClicked

    private void AnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnneeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Annee;
    private javax.swing.JTextField MATRICULE;
    public rojerusan.RSTableMetro Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private javax.swing.JTextField recherche;
    // End of variables declaration//GEN-END:variables
}
