/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package INTERFACE;

import BD.Connexion;
import CLASSESE.Employeurs;
import com.sun.java.swing.plaf.windows.WindowsScrollBarUI;
import java.awt.Color;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author KATALA
 */
public class VOIR_EMPLOYEUR extends javax.swing.JPanel {

    /**
     * Creates new form VOIR_EMPLOYEUR
     */
    Employeurs e = new Employeurs();
    MODIF_EMPLOYEURS ME = new MODIF_EMPLOYEURS();
    MENUS M = new MENUS();

    public VOIR_EMPLOYEUR() {
        initComponents();
        jScrollPane1.getHorizontalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getVerticalScrollBar().setUI(new WindowsScrollBarUI());
        jScrollPane1.getViewport().setBackground(Color.white);
        MATRICULE.setVisible(false);
        MATRICULE.setText(MENUS.vrai);

        if (MENUS.grades.equals("analyste")) {
            e.remplir(Table, "SELECT * FROM Employeurs where matricule='" + MENUS.vrai + "'");
        } else {
            e.remplir(Table, "SELECT * FROM Employeurs");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table = new rojerusan.RSTableMetro();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        recherche = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        kButton13 = new keeptoo.KButton();
        kButton12 = new keeptoo.KButton();
        kButton11 = new keeptoo.KButton();
        MATRICULE = new javax.swing.JTextField();
        Annee = new javax.swing.JTextField();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));

        Table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Titre 1", "Titre 2", "Titre 3", "Titre 4", "Titre 5", "Titre 6"
            }
        ));
        Table.setAltoHead(30);
        Table.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        Table.setColorBackgoundHead(new java.awt.Color(0, 26, 83));
        Table.setColorBordeHead(new java.awt.Color(0, 176, 80));
        Table.setColorFilasBackgound2(new java.awt.Color(238, 238, 238));
        Table.setColorFilasForeground1(new java.awt.Color(0, 0, 0));
        Table.setColorFilasForeground2(new java.awt.Color(0, 0, 0));
        Table.setColorSelBackgound(new java.awt.Color(0, 176, 80));
        Table.setFocusable(false);
        Table.setGrosorBordeFilas(0);
        Table.setGrosorBordeHead(0);
        Table.setIntercellSpacing(new java.awt.Dimension(0, 0));
        Table.setMultipleSeleccion(false);
        Table.setRowHeight(20);
        Table.setShowHorizontalLines(false);
        Table.setShowVerticalLines(false);
        Table.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table);

        jPanel2.setBackground(new java.awt.Color(0, 26, 83));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("LISTE DES EMPLOYEURS");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
        );

        recherche.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        recherche.setForeground(new java.awt.Color(102, 102, 102));
        recherche.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        recherche.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                rechercheCaretUpdate(evt);
            }
        });

        jLabel2.setForeground(new java.awt.Color(0, 102, 0));
        jLabel2.setText("RECHERCHER PAR :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ICONES/icons8_update.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        kButton13.setText("IMPRIMER UN MOIS");
        kButton13.setBorderPainted(false);
        kButton13.setkAllowGradient(false);
        kButton13.setkAllowTab(false);
        kButton13.setkBackGroundColor(new java.awt.Color(0, 26, 83));
        kButton13.setkBorderRadius(15);
        kButton13.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton13.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton13.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton13.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton13.setOpaque(false);
        kButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton13ActionPerformed(evt);
            }
        });

        kButton12.setText("IMPRIMER UN CENTRE");
        kButton12.setBorderPainted(false);
        kButton12.setkAllowGradient(false);
        kButton12.setkAllowTab(false);
        kButton12.setkBackGroundColor(new java.awt.Color(0, 26, 83));
        kButton12.setkBorderRadius(15);
        kButton12.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton12.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton12.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton12.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton12.setOpaque(false);
        kButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton12ActionPerformed(evt);
            }
        });

        kButton11.setText("IMPRIMER TOUT");
        kButton11.setBorderPainted(false);
        kButton11.setkAllowGradient(false);
        kButton11.setkAllowTab(false);
        kButton11.setkBackGroundColor(new java.awt.Color(0, 26, 83));
        kButton11.setkBorderRadius(15);
        kButton11.setkHoverColor(new java.awt.Color(102, 102, 102));
        kButton11.setkHoverForeGround(new java.awt.Color(255, 255, 255));
        kButton11.setkPressedColor(new java.awt.Color(0, 176, 80));
        kButton11.setkSelectedColor(new java.awt.Color(0, 176, 80));
        kButton11.setOpaque(false);
        kButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kButton11ActionPerformed(evt);
            }
        });

        Annee.setForeground(new java.awt.Color(0, 26, 83));
        Annee.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)), "ANNEE", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 26, 83))); // NOI18N
        Annee.setOpaque(false);
        Annee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AnneeMouseClicked(evt);
            }
        });
        Annee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AnneeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(kButton13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(MATRICULE, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addComponent(Annee, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(recherche, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(recherche, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(22, 22, 22))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(kButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(kButton13, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(MATRICULE, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(Annee, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 504, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void TableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TableMouseClicked
        //TODO add your handling code here:
        try {
            ME.setVisible(true);
        int ligne = Table.getSelectedRow();
        
            ME.id_employeur.setText(Table.getValueAt(ligne,0).toString());
            ME.EMPLOYEYRFICHER.setText(Table.getValueAt(ligne,1).toString());
            ME.PUBLIC1.setText(Table.getValueAt(ligne,2).toString());
            ME.FMOINS20S1.setText(Table.getValueAt(ligne,3).toString());
            ME.FPLUS20S1.setText(Table.getValueAt(ligne,4).toString());
            ME.FPRIVES1.setText(Table.getValueAt(ligne,5).toString());
            ME.FMOINS20S2.setText(Table.getValueAt(ligne,6).toString());
            ME.FPLUS20S2.setText(Table.getValueAt(ligne,7).toString());
            ME.GENSMAISON1.setText(Table.getValueAt(ligne,8).toString());
            ME.num9.setText(Table.getValueAt(ligne,9).toString());
            ME.num10.setText(Table.getValueAt(ligne,10).toString());
            ME.num11.setText(Table.getValueAt(ligne,11).toString());
            ME.num12.setText(Table.getValueAt(ligne,12).toString());
            ME.num13.setText(Table.getValueAt(ligne,13).toString());
            ME.num14.setText(Table.getValueAt(ligne,14).toString());
            ME.num15.setText(Table.getValueAt(ligne,15).toString());
            ME.num16.setText(Table.getValueAt(ligne,16).toString());
            ME.num17.setText(Table.getValueAt(ligne,17).toString());
            ME.num18.setText(Table.getValueAt(ligne,18).toString());
            ME.num19.setText(Table.getValueAt(ligne,19).toString());
            ME.num20.setText(Table.getValueAt(ligne,20).toString());
            ME.num21.setText(Table.getValueAt(ligne,21).toString());
            ME.num22.setText(Table.getValueAt(ligne,22).toString());
            ME.num23.setText(Table.getValueAt(ligne,23).toString());
            ME.num24.setText(Table.getValueAt(ligne,24).toString());
            ME.num25.setText(Table.getValueAt(ligne,25).toString());
            ME.num50.setText(Table.getValueAt(ligne,26).toString());
            ME.num49.setText(Table.getValueAt(ligne,27).toString());
            ME.num47.setText(Table.getValueAt(ligne,28).toString());
            ME.num44.setText(Table.getValueAt(ligne,29).toString());
            ME.num43.setText(Table.getValueAt(ligne,30).toString());
            ME.num40.setText(Table.getValueAt(ligne,31).toString());
            ME.num39.setText(Table.getValueAt(ligne,32).toString());
            ME.num33.setText(Table.getValueAt(ligne,33).toString());
            ME.num32.setText(Table.getValueAt(ligne,34).toString());
            ME.num31.setText(Table.getValueAt(ligne,35).toString());
            ME.num30.setText(Table.getValueAt(ligne,36).toString());
            ME.num28.setText(Table.getValueAt(ligne,37).toString());
            ME.num29.setText(Table.getValueAt(ligne,38).toString());
            ME.num51.setText(Table.getValueAt(ligne,39).toString());
            ME.num48.setText(Table.getValueAt(ligne,40).toString());
            ME.num46.setText(Table.getValueAt(ligne,41).toString());
            ME.num45.setText(Table.getValueAt(ligne,42).toString());
            ME.num42.setText(Table.getValueAt(ligne,43).toString());
            ME.num41.setText(Table.getValueAt(ligne,44).toString());
            ME.num38.setText(Table.getValueAt(ligne,45).toString());
            ME.num37.setText(Table.getValueAt(ligne,46).toString());
            ME.num36.setText(Table.getValueAt(ligne,47).toString());
            ME.num35.setText(Table.getValueAt(ligne,48).toString());
            ME.num34.setText(Table.getValueAt(ligne,49).toString());
            ME.num27.setText(Table.getValueAt(ligne,50).toString());
            ME.num26.setText(Table.getValueAt(ligne,51).toString());
            ME.num76.setText(Table.getValueAt(ligne,52).toString());
            ME.num75.setText(Table.getValueAt(ligne,53).toString());
            ME.num73.setText(Table.getValueAt(ligne,54).toString());
            ME.num70.setText(Table.getValueAt(ligne,55).toString());
            ME.num69.setText(Table.getValueAt(ligne,56).toString());
            ME.num66.setText(Table.getValueAt(ligne,57).toString());
            ME.num65.setText(Table.getValueAt(ligne,58).toString());
            ME.num59.setText(Table.getValueAt(ligne,59).toString());
            ME.num58.setText(Table.getValueAt(ligne,60).toString());
            ME.moisCB.setSelectedItem(Table.getValueAt(ligne,61).toString());
            ME.Annee.setText(Table.getValueAt(ligne,62).toString());
            ME.centreGestion.setSelectedItem(Table.getValueAt(ligne,63).toString());
            //ME.num54.setText(Table.getValueAt(ligne,64).toString());
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erreur de retoure : " + e.getMessage());
        }
    }//GEN-LAST:event_TableMouseClicked

    private void rechercheCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_rechercheCaretUpdate
        // TODO add your handling code here:
//        ex.remplir(Table, "SELECT * FROM examautres where id_examAutres like '%" + recherche.getText() + "%'");
    }//GEN-LAST:event_rechercheCaretUpdate

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        if (MENUS.grades.equals("analyste")) {
            e.remplir(Table, "SELECT * FROM Employeurs where matricule='" + MENUS.vrai + "'");
        } else {
            e.remplir(Table, "SELECT * FROM Employeurs");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void kButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton13ActionPerformed
        // TODO add your handling code here:
        try {
            if (MENUS.grades.equals("analyste")) {
                String query = "SELECT \n"
                        + "    c.nom,\n"
                        + "    c.Code_centre,\n"
                        + "    e.Employeurs_au_fichier,\n"
                        + "    e.Nouvelles_affiliations1,\n"
                        + "    e.Employeurs_en_activite,\n"
                        + "    e.Employeurs_ayant_declare,\n"
                        + "    e.Employeurs_ayant_cotise,\n"
                        + "    e.Employeurs_en_cessation,\n"
                        + "    e.mois,\n"
                        + "    e.annee\n"
                        + "FROM employeurs AS e\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=e.Code_centre\n"
                        + "WHERE e.annee='" + Annee.getText() + "' AND e.mois='" + recherche.getText() + "' AND e.Matricule='" + MATRICULE.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\EMPLOYEURSMOISMAT.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);

            } else {
                String query = "SELECT \n"
                        + "    c.nom,\n"
                        + "    c.Code_centre,\n"
                        + "    e.Employeurs_au_fichier,\n"
                        + "    e.Nouvelles_affiliations1,\n"
                        + "    e.Employeurs_en_activite,\n"
                        + "    e.Employeurs_ayant_declare,\n"
                        + "    e.Employeurs_ayant_cotise,\n"
                        + "    e.Employeurs_en_cessation,\n"
                        + "    e.mois,\n"
                        + "    e.annee\n"
                        + "FROM employeurs AS e\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=e.Code_centre\n"
                        + "WHERE e.annee='" + Annee.getText() + "' AND e.mois='" + recherche.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\EMPLOYEURSMOISTOUS.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);
            }

        } catch (JRException ex) {
            Logger.getLogger(VOIR_EMPLOYEUR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton13ActionPerformed

    private void kButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton12ActionPerformed
        // TODO add your handling code here:
        try {
            if (MENUS.grades.equals("analyste")) {
                String query = "SELECT \n"
                        + "    c.nom,\n"
                        + "    c.Code_centre,\n"
                        + "    e.Employeurs_au_fichier,\n"
                        + "    e.Nouvelles_affiliations1,\n"
                        + "    e.Employeurs_en_activite,\n"
                        + "    e.Employeurs_ayant_declare,\n"
                        + "    e.Employeurs_ayant_cotise,\n"
                        + "    e.Employeurs_en_cessation,\n"
                        + "    e.mois,\n"
                        + "    e.annee\n"
                        + "FROM employeurs AS e\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=e.Code_centre\n"
                        + "WHERE e.annee='" + Annee.getText() + "' AND e.Code_centre='" + recherche.getText() + "' AND e.Matricule='" + MATRICULE.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\EMPLOYEURSCENTREMAT.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);

            } else {

                String query = "SELECT \n"
                        + "    c.nom,\n"
                        + "    c.Code_centre,\n"
                        + "    e.Employeurs_au_fichier,\n"
                        + "    e.Nouvelles_affiliations1,\n"
                        + "    e.Employeurs_en_activite,\n"
                        + "    e.Employeurs_ayant_declare,\n"
                        + "    e.Employeurs_ayant_cotise,\n"
                        + "    e.Employeurs_en_cessation,\n"
                        + "    e.mois,\n"
                        + "    e.annee\n"
                        + "FROM employeurs AS e\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=e.Code_centre\n"
                        + "WHERE e.annee='" + Annee.getText() + "' AND e.Code_centre='" + recherche.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\EMPLOYEURSCENTRETOUS.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);
            }

        } catch (JRException ex) {
            Logger.getLogger(VOIR_EMPLOYEUR.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_kButton12ActionPerformed

    private void kButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kButton11ActionPerformed
        // TODO add your handling code here:
        try {
            if (MENUS.grades.equals("analyste")) {
                String query = "SELECT \n"
                        + "    c.nom,\n"
                        + "    e.Employeurs_au_fichier,\n"
                        + "    e.Nouvelles_affiliations1,\n"
                        + "    e.Employeurs_en_activite,\n"
                        + "    e.Employeurs_ayant_declare,\n"
                        + "    e.Employeurs_ayant_cotise,\n"
                        + "    e.Employeurs_en_cessation,\n"
                        + "    e.mois,\n"
                        + "    e.annee\n"
                        + "FROM employeurs AS e\n"
                        + "INNER JOIN centre_gestion AS c ON c.Code_centre=e.Code_centre\n"
                        + "WHERE e.annee='" + Annee.getText() + "' AND e.Matricule='" + MATRICULE.getText() + "'\n"
                        + "ORDER BY c.nom";

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\EMPLOYEURSTOUSNUM1MAT.jrxml");
                JRDesignQuery querynew = new JRDesignQuery();
                querynew.setText(query);
                jd.setQuery(querynew);
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                JasperPrint jp = JasperFillManager.fillReport(rapport, null, new Connexion().con());
                JasperViewer.viewReport(jp, false);

            } else {

                JasperDesign jd = JRXmlLoader.load("src\\ETATRAPPORT\\EMPLOYEURSTOUSNUM1.jrxml");
                JasperReport rapport = JasperCompileManager.compileReport(jd);
                String valeur = Annee.getText() + "%";
                Map param = new HashMap();
                param.put("ID", valeur);
                JasperPrint jp = JasperFillManager.fillReport(rapport, param, new Connexion().con());
                JasperViewer.viewReport(jp, false);
            }

        } catch (JRException ex) {
            Logger.getLogger(VOIR_EMPLOYEUR.class.getName()).log(Level.SEVERE, null, ex);
        }

    }//GEN-LAST:event_kButton11ActionPerformed

    private void AnneeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AnneeMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_AnneeMouseClicked

    private void AnneeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AnneeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AnneeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Annee;
    private javax.swing.JTextField MATRICULE;
    public rojerusan.RSTableMetro Table;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KButton kButton11;
    private keeptoo.KButton kButton12;
    private keeptoo.KButton kButton13;
    private javax.swing.JTextField recherche;
    // End of variables declaration//GEN-END:variables
}
